#!/bin/bash

#------------------------------------------------------
# Prerequisites are compiled here






#------------------------------------------------------
# compile the main program
g++ -o ChessTrack CMT.cpp



